"""Guards for the site's discovery layer (sitemap, robots.txt, llms.txt).

Three problems this file is here to prevent:

1. The homepage is a single-page app — its alert board only exists after
   JavaScript fetches ``data/auto-jobs.json``. Crawlers that never run
   JavaScript (Googlebot's secondary pass and the AI answer engines) used to
   get an empty page, and ``sitemap.xml`` listed just two URLs while 500+
   static, canonical alert pages sat undiscoverable in ``share/``.
2. ``robots.txt`` previously said nothing about AI crawlers, so a future
   default-deny policy at the host or CDN level would silently remove the
   site from ChatGPT / Gemini / Perplexity answers.
3. These files are generated by ``scripts/build_seo.py`` on every scheduled
   run. A hand edit would be lost on the next run, so the tests below pin the
   contract the generator must keep satisfying.
"""

import json
import re
import sys
import unittest
import xml.etree.ElementTree as ElementTree
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import build_seo  # noqa: E402
import build_share_pages  # noqa: E402

BASE_URL = build_seo.BASE_URL
SITEMAP = ROOT / "sitemap.xml"
ROBOTS = ROOT / "robots.txt"
LLMS = ROOT / "llms.txt"
SHARE_DIR = ROOT / "share"

SAMPLE_JOB = {
    "id": 225794245619041,
    "title": ("Central University of Punjab (CUPB), Bathinda — Laboratory Attendant "
              "(Pharmaceutical Sciences & Natural Products) Recruitment"),
    "department": "Central University of Punjab (CUPB), Bathinda",
    "vacancies": "1 Post (01-OBC)",
    "qualification": "10+2 with Science stream from a recognised Central/State Board",
    "qualCategory": "12th",
    "lastDate": "14-09-2026",
    "age": "18-30 Years (as on the date of interview)",
    "feeGen": "Rs. 100/-",
    "feeSC": "Nil (SC/ST/PWD/Women exempt)",
    "location": "Bathinda, Punjab",
    "applyMode": "Online",
    "advtNo": "CUPB/26-27/012 dated 02.09.2026",
    "alertType": "recruitment",
    "type": "central",
    "publishedAt": "2026-09-02T00:00:00+05:30",
    "discoveredAt": "2026-09-11T02:15:13Z",
    "pdfLink": "https://cup.edu.in/sites/default/files/Contract%20NT_09_2026.pdf",
    "applyLink": "https://cupnt.samarth.edu.in/index.php/site/login",
    "details": ("…on purely temporary and contractual basis for 89 days. "
                "Emoluments Rs. 28,800/- per month."),
}


class SitemapTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = SITEMAP.read_text(encoding="utf-8")
        cls.root = ElementTree.fromstring(cls.text)
        cls.locs = [element.text for element in cls.root.iter(
            "{http://www.sitemaps.org/schemas/sitemap/0.9}loc")]

    def test_sitemap_is_valid_xml(self):
        self.assertTrue(self.locs)
        self.assertTrue(all(loc.startswith("https://") for loc in self.locs))

    def test_sitemap_lists_the_homepage(self):
        self.assertIn(f"{BASE_URL}/", self.locs)

    def test_sitemap_lists_every_article_page(self):
        for name in build_seo.ARTICLE_PAGES:
            with self.subTest(page=name):
                self.assertIn(f"{BASE_URL}/{name}", self.locs)

    def test_sitemap_lists_every_share_page(self):
        """Every alert page must be discoverable, not just the homepage."""
        share_pages = sorted(SHARE_DIR.glob("job-*.html"))
        self.assertTrue(share_pages, "expected share/job-*.html pages to exist")
        missing = [path.name for path in share_pages
                   if f"{BASE_URL}/share/{path.name}" not in self.locs]
        self.assertEqual([], missing[:10], f"{len(missing)} alert pages are not in the sitemap")

    def test_sitemap_has_no_internal_redirect_pages(self):
        self.assertNotIn(f"{BASE_URL}/redirect.html", self.locs)

    def test_every_entry_carries_a_lastmod(self):
        namespace = "{http://www.sitemaps.org/schemas/sitemap/0.9}"
        for url in self.root.iter(f"{namespace}url"):
            self.assertIsNotNone(url.find(f"{namespace}lastmod"))

    def test_sitemap_stays_within_the_protocol_limits(self):
        self.assertLessEqual(len(self.locs), 50000)


class RobotsTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = ROBOTS.read_text(encoding="utf-8")

    def test_everyone_is_allowed(self):
        self.assertRegex(self.text, r"User-agent:\s*\*\s*\nAllow:\s*/")

    def test_ai_answer_engines_are_explicitly_allowed(self):
        for crawler in ("GPTBot", "OAI-SearchBot", "ChatGPT-User", "PerplexityBot",
                        "ClaudeBot", "anthropic-ai", "Google-Extended",
                        "Applebot-Extended"):
            with self.subTest(crawler=crawler):
                self.assertIn(f"User-agent: {crawler}", self.text)

    def test_sitemap_is_declared(self):
        self.assertIn(f"Sitemap: {BASE_URL}/sitemap.xml", self.text)

    def test_llms_index_is_advertised(self):
        self.assertIn("llms.txt", self.text)

    def test_application_plumbing_is_not_crawled(self):
        self.assertRegex(self.text, r"Disallow:\s*/data/")


class LlmsTxtTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = LLMS.read_text(encoding="utf-8")

    def test_file_has_the_required_shape(self):
        self.assertTrue(self.text.startswith("# EMPLOYMENT EXPRESS"))
        self.assertIn(">", self.text.split("\n")[2])

    def test_it_explains_how_alerts_are_verified(self):
        lowered = self.text.lower()
        self.assertIn("official", lowered)
        self.assertIn("punjab", lowered)

    def test_every_linked_page_exists(self):
        links = re.findall(r"\((https://[^)]+)\)", self.text)
        self.assertTrue(links)
        for link in links:
            with self.subTest(link=link):
                relative = link.replace(f"{BASE_URL}/", "")
                self.assertTrue((ROOT / relative).exists(), f"missing page: {link}")

    def test_expired_alerts_are_kept_out_of_the_index(self):
        """An assistant must never quote a deadline that has already passed."""
        today = "2026-09-11"
        expired = build_seo._is_expired({"lastDate": "09-09-2026"}, today)
        live = build_seo._is_expired({"lastDate": "15-09-2026"}, today)
        undated = build_seo._is_expired({"lastDate": "See Notification"}, today)
        self.assertTrue(expired)
        self.assertFalse(live)
        self.assertFalse(undated)


class SharePageMarkupTests(unittest.TestCase):
    """Each alert page must stand on its own for a crawler that runs no JS."""

    @classmethod
    def setUpClass(cls):
        cls.html = build_share_pages.share_page_html(SAMPLE_JOB)

    def test_structured_data_is_static_and_parses(self):
        match = re.search(r'<script type="application/ld\+json">(.*?)</script>',
                          self.html, re.S)
        self.assertIsNotNone(match, "no JSON-LD block on the share page")
        raw = match.group(1).replace("<\\/", "</").replace("<\\!--", "<!--")
        data = json.loads(raw)
        types = [node.get("@type") for node in data["@graph"]]
        self.assertIn("JobPosting", types)
        self.assertIn("BreadcrumbList", types)

    def test_jobposting_carries_the_fields_google_requires(self):
        match = re.search(r'<script type="application/ld\+json">(.*?)</script>',
                          self.html, re.S)
        data = json.loads(match.group(1).replace("<\\/", "</"))
        posting = next(node for node in data["@graph"]
                       if node.get("@type") == "JobPosting")
        self.assertTrue(posting["title"])
        self.assertTrue(posting["description"])
        self.assertRegex(posting["datePosted"], r"^\d{4}-\d{2}-\d{2}$")
        self.assertRegex(posting["validThrough"], r"^\d{4}-\d{2}-\d{2}$")
        self.assertEqual(posting["jobLocation"]["address"]["addressCountry"], "IN")
        self.assertTrue(posting["hiringOrganization"]["name"])
        self.assertIn("url", posting)
        # The stored monthly emolument is picked up, never invented.
        self.assertEqual(posting["baseSalary"]["value"]["value"], 28800)
        self.assertEqual(posting["baseSalary"]["currency"], "INR")

    def test_page_has_its_own_keywords_and_canonical(self):
        self.assertIn('<meta name="keywords"', self.html)
        self.assertIn(f'<link rel="canonical" href="{BASE_URL}/share/job-225794245619041.html">',
                      self.html)
        self.assertIn("CUPB", self.html)

    def test_no_meta_refresh_redirect(self):
        """A 0-second meta refresh would flag the page as a redirect and cost
        it the index; the redirect to the app is JavaScript-only."""
        self.assertNotIn("http-equiv", self.html)
        self.assertIn("window.location.replace", self.html)

    def test_the_page_shows_the_alert_details_as_text(self):
        for value in ("Laboratory Attendant", "1 Post (01-OBC)", "14-09-2026",
                      "Bathinda, Punjab", "CUPB/26-27/012"):
            with self.subTest(value=value):
                self.assertIn(value, self.html)
        self.assertIn("Official notification", self.html)
        self.assertIn("Apply online", self.html)


class BuildSeoContractTests(unittest.TestCase):
    def test_builder_is_deterministic(self):
        jobs = build_seo.load_jobs()
        today = "2026-09-11"
        self.assertEqual(build_seo.build_sitemap(jobs, today),
                         build_seo.build_sitemap(jobs, today))
        self.assertEqual(build_seo.build_llms_txt(jobs, today),
                         build_seo.build_llms_txt(jobs, today))
        self.assertEqual(build_seo.build_robots_txt(), build_seo.build_robots_txt())

    def test_builder_only_writes_the_three_discovery_files(self):
        protected = ("index.html", "assets/logo.png")
        before = [(path, (ROOT / path).read_bytes()) for path in protected
                  if (ROOT / path).exists()]
        # The builder's output is date-sensitive: alerts whose last date has
        # just passed drop out of llms.txt/sitemap.xml, so calling main() on
        # the day after the files were committed rewrites them and leaves the
        # working tree dirty. That made the scheduled workflow's
        # "Commit newly discovered alerts" step fail its unstaged-changes
        # guard (instantly, before pushing) on the first run after a UTC
        # date rollover. Snapshot the three discovery files and restore them
        # afterwards - the workflow regenerates them in its own
        # "Refresh SEO discovery files" step, so the test suite must not
        # modify them.
        discovery = (build_seo.SITEMAP, build_seo.LLMS_TXT, build_seo.ROBOTS_TXT)
        snapshots = [(path, path.read_bytes()) for path in discovery if path.exists()]
        try:
            build_seo.main()
        finally:
            for path, content in before:
                if (ROOT / path).read_bytes() != content:
                    (ROOT / path).write_bytes(content)
                    self.fail(f"build_seo.main() modified protected file {path}")
            for path, content in snapshots:
                if path.read_bytes() != content:
                    path.write_bytes(content)

    def test_homepage_lastmod_tracks_the_newest_alert(self):
        jobs = [{"id": 1, "discoveredAt": "2026-09-10T00:00:00Z"},
                {"id": 2, "discoveredAt": "2026-09-11T00:00:00Z"}]
        sitemap = build_seo.build_sitemap(jobs, "2026-09-11")
        self.assertIn("<lastmod>2026-09-11</lastmod>", sitemap.split("</url>")[0])


if __name__ == "__main__":
    unittest.main()
